### ISSUE TITLE
Overwrite of the n-gram config values.

### ISSUE THREAD

**Issue by amasend** [echr-od/ECHR-OD_process#15]
This line of code overwrites all n-grams config configuration in normalization step.

https://github.com/aquemy/ECHR-OD_process/blob/faff176293314816e470e3798df428e97bdf3e9d/normalize_documents.py#L54

Should be moved to "if" statement.

**Comment by aquemy** [comment]
It does not impact the release 1.0.x since it is intended to have n-grams from 1 to 4 and no filter by frequency.

However, this need to be urgently changed in the development version (branch ```develop```).
