### ISSUE TITLE
Parsing texts with special characters

### ISSUE THREAD

**Issue by plison** [echr-od/ECHR-OD_process#152]
I've noticed that court cases such as [001-83979](https://echr-opendata.eu/cases/001-83979#) do not seem to be parsed correctly, as some named entities are missing (see for instance point 2., which should be "Diyarbakır"). 

As the missing tokens in this example have special Turkish characters, I assume the problem is due to some encoding issues? (but what makes it strange is that "Diyarbakır" is actually correctly parsed at other places in the document).

**Comment by plison** [comment]
It seems the error is due to `python-docx` - I get the same missing words when I read the text directly through that library. However, the extracted text looks fine if I run `[docx2txt](https://github.com/ankushshah89/python-docx2txt)` instead of `docx`, which indicates this is probably a bug in `python-docx`. Very annoying though, since it's hard to know whether this is an isolated error, or whether this is something more widespread.

**Comment by plison** [comment]
I digged some more on this issue, it seems that the problem is unfortunately quite widespread, I wrote a small script to search for similar errors (comparing the text for each case with the result of docx2txt) and I found hundreds of similar errors :-(

**Comment by aquemy** [comment]
If you could share the script that would be awesome! I could integrate it in the build process as QA check to flag the problematic cases.
When we would have a clear view of the impact, we might decide to change for another library or monkey patch if possible.

**Comment by plison** [comment]
I made a few tests with various tools, and here is what I found:
- `python-docx` seems to have some serious issues where entire text fragments are missing, so I would not rely on it at all
- `docx2txt` works better, and does not seems to skip those fragments. However, there are still a few issues, notably the fact that the numbers for the headings (1., 2., etc.) are missing, which makes it hard to get the full structure of the court case. 
- the tool I found that actually gave the best conversion quality was actually LibreOffice. I found out you can directly convert a docx document to a txt file from the command line, like this:
```
/path/to/libreoffice --headless --norestore --convert-to txt test.docx --outdir  /txt
```
Of course, this requires you to install LibreOffice, and it's not something you can run `pip install` on. But the quality of the conversion is much better than other libraries (which is not too surprising, given the fact it's a much more advanced tool for reading `docx` documents).

I ran it over the full set of `docx`files in [ECHR-OpenData](https://echr-opendata.eu/download/2.0.0/raw/judgments/docx) and it worked quite well. It takes a few hours, however.

**Comment by aquemy** [comment]
Thanks!

I will try to look for a Pythonic alternative, maybe fixing myself `python-docx` or `docx2txt` depending on which one seems easier to fix.
Last resort, as the whole process is containerized it is possible to add LibreOffice as a dependency.

**Comment by aquemy** [comment]
After investigation, it does not really seem to be a bug in python-docx but a problem in the Word document itself.

It was enough to open the document in LibreOffice and save it again in the same format (MS Word 2006).
However, it complains about the fact that some formatting might be lost.

What I have done is to try to compare the original word structure and the reformated one. There are significant differences in the hierarchy but I do not know how much it effectively affect the content.

An interesting finding though:

In the original document, the missing word is in sequence of smart tag (and it indicates the type of entity which is great for future work on entity extraction):
```
<w:smartTag w:uri="urn:schemas-microsoft-com:office:smarttags" w:element="place">
<w:smartTag w:uri="urn:schemas-microsoft-com:office:smarttags" w:element="City">
<w:r w:rsidRPr="00347DD8">
<w:rPr>
<w:rStyle w:val="JuParaCar"/>
</w:rPr>
<w:t>Diyarbakır</w:t>
</w:r>
</w:smartTag>
</w:smartTag>
```

In comparison, a proper 2006 word document:
```
<w:r>
<w:rPr>
<w:rStyle w:val="JuParaCar"/>
</w:rPr>
<w:t xml:space="preserve">The applicants were represented by Mr F. Gümüş, a lawyer practising in Diyarbakır. </w:t>
</w:r>
```

There might be something wrong about the SmartTage and that is the reason why it is not parsed by python-docx.
Other libraries might convert themselved into an intermediate representation and lose track of these smart tags.

I need more time/investigation to understand if there is a way to easily keep the tags (and if we want to), and how to help python-docx to properly take them into account.

**Comment by aquemy** [comment]
It has been reported for more than 4 years and it does not seem it will ever be fixed:
- https://github.com/python-openxml/python-docx/issues/339 (in particular: https://github.com/python-openxml/python-docx/issues/339#issuecomment-266117476)
- https://github.com/python-openxml/python-docx/issues/335#issuecomment-261603444

This leaves us with two choices:
- finding a library that can handle smarttags (could be handy for entity extraction) and keep proper format to replace `python-docx`. 
   -    Pro: keep smart tags, 
   -    Con: lot of effort in refactoring
- converting each document into a proper format e..g. Word 2006, such that the smarttages are removed. Could be done programatically in python I believe.
   -   Pro: No refactoring
   -   Con: Losing smart tags, possibility to alter formatting/lose information (to evaluate)

**Comment by plison** [comment]
Thanks for investigating this. Although I understand your preference for a purely Pythonic alternative, I would also suggest a third choice, namely use the conversion functionalities from OpenOffice or LibreOffice. 

Although installing those programs themselves needs to be done outside `pip`, it's quite easy to interface them with Python (either programmatically, or by running command line scripts).  From what I could see, the conversion was much better than what I could achieve with both `python-docx` and `doc2txt`. For instance, the numbering in sections, subsections was sometimes gone with `python-docx` and `doc2txt`, but was correctly extracted with LibreOffice. 

The conversion is a bit slower, but I managed to convert the full database of Word documents in a few hours (using the `headless` mode).

**Comment by aquemy** [comment]
I actually have a working simple fix that still uses `python-docx` (see here: https://github.com/echr-od/ECHR-OD_process/pull/164).

As it might impact potentially all documents, I'll make a dry run locally before regenerating the database in 10 days.

Currently, the biggest struggle I have is the CPU and RAM limitation on the small server, so I try to avoid any additional overhead. I am currently looking for stable fundings that would cover some better hardware.
